name: Build Engine
on:
  workflow_dispatch:
  schedule:
    - cron: "36 00 * * *"
jobs:
  build-engine:
    strategy:
      matrix:
        system:
          - amd64-linux
          - amd64-windows
    runs-on:
      - nscloud-ubuntu-24.04-amd64-8x16-with-cache
      - nscloud-cache-tag-engine-${{ matrix.system }}
      - nscloud-cache-size-20gb
      - nscloud-git-mirror-5gb
      - nscloud-exp-container-image-cache
    steps:
      - name: Checkout code
        uses: namespacelabs/nscloud-checkout-action@v5
        with:
          fetch-depth: 0
          submodules: recursive
          dissociate: true
          path: src
      - name: Setup ccache cache
        uses: namespacelabs/nscloud-cache-action@v1
        with:
          path: ccache
      - name: Build
        # Instead of manually running docker, it would be cool to just run whole GitHub actions
        # in container, but unfortunately ubuntu 18.04 is just too old to be able to do it ;(.
        run: |
          mkdir -p ccache target
          docker run --rm \
            -v /etc/passwd:/etc/passwd:ro \
            -v /etc/group:/etc/group:ro \
            --user="$(id -u):$(id -g)" \
            -v $(pwd)/src:/build/src:ro \
            -v $(pwd)/ccache:/build/cache:rw \
            -v $(pwd)/target:/build/target:rw \
            ghcr.io/${{ github.repository_owner }}/recoil-build-${{ matrix.system }}:latest \
            bash -c './bin/cmake_config && cd out && ninja && ninja install'
      - name: Save
        uses: namespace-actions/upload-artifact@v0
        with:
          name: output-${{ matrix.system }}
          path: ./target
